<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="jinsu.jinsu_page.repository.MemoryMemberRepositoryTest" tests="2" skipped="0" failures="1" errors="0" timestamp="2024-06-24T10:31:51" hostname="LAPTOP-KAMV933P" time="0.058">
  <properties/>
  <testcase name="findAll()" classname="jinsu.jinsu_page.repository.MemoryMemberRepositoryTest" time="0.054">
    <failure message="org.opentest4j.AssertionFailedError: &#13;&#10;expected: 3&#13;&#10; but was: 2" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: 
expected: 3
 but was: 2
	at java.base@17.0.11/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.11/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at app//jinsu.jinsu_page.repository.MemoryMemberRepositoryTest.findAll(MemoryMemberRepositoryTest.java:47)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.11/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.11/java.util.ArrayList.forEach(ArrayList.java:1511)
</failure>
  </testcase>
  <testcase name="save()" classname="jinsu.jinsu_page.repository.MemoryMemberRepositoryTest" time="0.003"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
